# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version 
Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = "v"
    ansible.playbook = "../Ansible/playbook.yml"
    roles_path    = "../Ansible/roles"
  end

  # Port mapping which allows access to a specific port within the machine 
  # from a port on the host machine. 
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 5000, host: 5000

  # Share an additional folder to the guest 
  config.vm.synced_folder "../", "/supersnake"
  
end
